kari, script, 2mp3: improve

diff --git a/home-manager/users/kari/scripts/2mp3 b/home-manager/users/kari/scripts/2mp3
--- a/home-manager/users/kari/scripts/2mp3
+++ b/home-manager/users/kari/scripts/2mp3
@@ -1,12 +1,42 @@
 #!/usr/bin/env bash
 
+# Function to display usage information
+usage() {
+  echo "usage: $0 <directory> [--cleanup]"
+  exit 1
+}
+
+# Check if at least one argument is passed
+[ $# -lt 1 ] && usage
+
+# Initialize variables
+directory=""
+cleanup=false
+
+# Parse arguments
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    --cleanup)
+      cleanup=true
+      shift
+      ;;
+    *)
+      directory="$1"
+      shift
+      ;;
+  esac
+done
+
+# Ensure a directory is provided
+[ -z "$directory" ] && usage
+
 # Function to convert audio files to MP3
 convert_to_mp3() {
-  find . -type f -name "*.$1" -exec sh -c 'ffmpeg -i "$0" -b:a 320k -map_metadata 0 -id3v2_version 3 "${0%.$1}.mp3"' {} \;
+  find "$directory" -type f -name "*.$1" -exec sh -c 'ffmpeg -i "$0" -b:a 320k -map_metadata 0 -id3v2_version 3 "${0%.$1}.mp3"' {} \;
 }
 
 # Array of file extensions to convert
-extensions=("flac" "m4a")
+extensions=("flac" "m4a" "wav")
 
 # Loop through the array and convert each extension to MP3
 for ext in "${extensions[@]}"; do
@@ -14,7 +44,15 @@ for ext in "${extensions[@]}"; do
 done
 
 # Remove non-MP3 files
-find . -type f ! -name "*.mp3" -exec rm {} \;
+for ext in "${extensions[@]}"; do
+  find "$directory" -type f -name "*.$ext" -exec rm {} \;
+done
 
-# Remove empty directories
-find . -type d -empty -delete
+# Conditional cleanup
+if [ "$cleanup" = true ]; then
+  find "$directory" -type f ! -name "*.mp3" \
+    ! -name "*.zip" ! -name "*.tar" ! -name "*.gz" ! -name "*.bz2" ! -name "*.7z" ! -name "*.rar" \
+    -exec rm {} \;
+  find "$directory" -type d -empty -delete
+fi
+
